# Generated by Django 4.2.1 on 2023-05-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('years_old', models.IntegerField()),
                ('email', models.TextField(max_length=255)),
                ('cpf', models.TextField(max_length=11)),
                ('card_number', models.TextField(max_length=16)),
                ('cvv', models.TextField(max_length=3)),
            ],
        ),
    ]
