# Generated by Django 4.2.1 on 2023-05-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_first_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
